Debug: false
Slots:
  MainHand: 'MainHand'
  Register:
    36: 'Boots'
    37: 'Leggings'
    38: 'Chest'
    39: 'Helmet'
    40: 'OffHand'
StatusInfo:
  Messages:
    - '&f&l%player_name% &bStatusInfo'
    - '&8PhysicalDamage: &f%Arathoth_Primary_PhysicalDamage%'
  RegisteredPAPI:
    - '%Arathoth_Primary_PhysicalDamage%'
  MinLines: 1
  HideTitleMessage:
    Title: '&8&lSorry!'
    SubTitle: '&7&lYou have no status!'
DecimalFormat: '0.0'
ActionBarMessageRemind: true